import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/intro',
        'getting-started/installation',
        'getting-started/quickstart',
        'getting-started/comparison',
        'getting-started/concepts',
      ],
    },
  ],

  algorithmsSidebar: [
    {
      type: 'category',
      label: 'Algorithms',
      collapsed: false,
      items: [
        'algorithms/overview',
        'algorithms/rvq',
        'algorithms/vecinfer',
        'algorithms/ratequant',
        'algorithms/spectral',
        'algorithms/rabitq',
        'algorithms/qjl',
        'algorithms/polarquant',
        'algorithms/commvq',
        'algorithms/nsnquant',
        'algorithms/kivi',
        'algorithms/kivi-sink',
        'algorithms/skvq',
        'algorithms/svdq',
        'algorithms/kitty',
        'algorithms/adakv',
        'algorithms/xquant',
        'algorithms/kvquant',
        'algorithms/palu',
        'algorithms/cachegen',
        'algorithms/minicache',
        'algorithms/gear',
        'algorithms/zipcache',
        'algorithms/snapkv',
        'algorithms/streaming_llm',
        'algorithms/h2o',
        'algorithms/tova',
        'algorithms/pyramidkv',
        'algorithms/squeeze',
        'algorithms/chunkkv',
        'algorithms/cam',
        'algorithms/knorm',
        'algorithms/qfilters',
        'algorithms/keyformer',
        'algorithms/morphkv',
        'algorithms/kvzip',
        'algorithms/kvtc',
        'algorithms/curdkv',
        'algorithms/nestedkv',
        'algorithms/amc',
        'algorithms/a2ats',
        'algorithms/anchorkv',
        'algorithms/rocketkv',
        'algorithms/xkv',
        'algorithms/cross-model-transfer',
      ],
    },
  ],

  guidesSidebar: [
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/control-panel',
        'guides/mlx-lm-integration',
        'guides/metal-kernels',
        'guides/calibration',
        'guides/mixed-precision',
        'guides/sliding-window',
        'guides/observers',
        'guides/profiling',
        'guides/benchmarking',
        'guides/validation-report',
        'guides/mac-recommender',
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api/cache',
        'api/quantizers',
        'api/allocators',
        'api/memory-api',
        'api/spectral-api',
        'api/metal-api',
        'api/observers-api',
        'api/profiling-api',
        'api/core-api',
        'api/exceptions-api',
      ],
    },
  ],
};

export default sidebars;
