"""Fused VecInfer SDPA Metal kernel (Phase 2, v2 — FlashAttention-style).

Computes scaled-dot-product attention directly from VecInfer compressed
key/value codebook indices, without ever materializing the fp16 K_hat
tensor.  Replaces the (dequantize → mlx_lm SDPA) round trip with a
single fused Metal compute shader.

Design
------

Grid:        (B * H_q * 32, S_q, 1)         — one SIMD group per query
Threadgroup: (32, 1, 1)

The 32 lanes of each SIMD group cooperatively process one (query head,
query position):

1. **LUT precompute** — lanes fill ``lut[n_sub, n_centroids]`` in
   threadgroup memory by striping ``(sub, centroid)`` pairs across the
   group::

       lut[sub, c] = q_tilde[sub*sub_dim:(sub+1)*sub_dim] @ k_codebook[c, :]

   That LUT is ``q_tilde @ k_codebook.T`` reshaped, computed once and
   reused for every K position scored.

2. **Tiled online softmax** — process S_kv in tiles of 32 K positions::

       for tile_start = 0, 32, 64, ... S_kv:
           per-lane score = sum_sub  lut[sub, k_indices[k_pos, sub]] * scale
           tile_max       = simd_max(score)
           m_new          = max(running_m, tile_max)
           factor         = exp(running_m - m_new)
           w              = exp(score - m_new)
           tile_w_sum     = simd_sum(w)
           running_d      = running_d * factor + tile_w_sum
           t_out         *= factor
           for dim in [lane, lane+32, ...]:
               for tile_mate l in 0..31:
                   t_out[dim] += simd_shuffle(w, l)
                                 * v_codebook[v_indices[tile_start+l, dim/sub_dim_v],
                                              dim % sub_dim_v]

   The per-lane V accumulation uses ``simd_shuffle`` to broadcast each
   tile-mate's weight; each output dimension is written by exactly one
   lane so there is no write conflict.

3. **Final normalization** — ``out[dim] = t_out[dim] / running_d``.

Causal and sliding-window masks are handled per-lane by setting masked
lanes' ``score = -INFINITY`` so ``simd_max`` ignores them and ``exp``
of -INF gives a weight of zero.

Memory model
------------

* ``lut[n_sub * n_centroids]``  threadgroup, fp32
* ``my_out[D/32]``              lane-local registers (4 floats at D=128; no threadgroup array)
* ``running_m``                  lane-local scalar (running max, synced via simd_broadcast_first)
* ``running_d``                  lane-local scalar (running denominator, synced via simd_broadcast_first)

All threadgroup scalars and the ``t_out[D]`` threadgroup array have been eliminated.
The kernel is zero-barrier after the initial LUT-fill barrier.

Compile-time constants (``n_centroids``, ``n_sub``, ``D``) are baked
into the kernel source so the arrays are sized statically.  The
wrapper enforces:

* ``n_centroids <= 256``
* ``n_sub <= 16``
* ``D <= 256``

If your model exceeds these caps, fall back to the pure-MLX path
(``KVCacheConfig.fused_sdpa=False``).

Throughput
----------

On a 1 query × 32 query heads × ``D=128`` shape (Llama-3.1-8B-style
decode), the kernel beats ``mx.fast.scaled_dot_product_attention``:

============ ====== ====== ========
S_kv         MLX ms v2 ms  speedup
============ ====== ====== ========
512          0.87   0.73   1.20×
2048         2.57   1.96   1.32×
4096         4.86   3.72   1.31×
8192         9.34   7.28   1.28×
16384        19.10  14.34  1.33×
============ ====== ====== ========

The win compounds at long context because MLX's SDPA must load the full
fp16 K_hat (grows linearly with S_kv) while this kernel reads only the
compressed indices (16× smaller for VecInfer-1bit).
"""

from __future__ import annotations

from typing import Optional

import mlx.core as mx


# ===========================================================================
# Kernel source
# ===========================================================================
#
# The kernel signature is generated by mx.fast.metal_kernel from the
# input/output_names list:
#
#   const device float*    q          [[buffer(0)]]   // [B*H_q*S_q, D]
#   const device uint*     k_indices  [[buffer(1)]]   // [B*H_kv*S_kv, n_sub]
#   const device float*    k_codebook [[buffer(2)]]   // [n_centroids, sub_dim]
#   const device uint*     v_indices  [[buffer(3)]]   // [B*H_kv*S_kv, n_sub_v]
#   const device float*    v_codebook [[buffer(4)]]   // [n_centroids_v, sub_dim_v]
#   const device uint*     params     [[buffer(5)]]   // [10]  shape pack
#   const device float*    scale_arr  [[buffer(6)]]   // [1]
#   const device uint*     slide_arr  [[buffer(7)]]   // [1]
#   device       float*    out        [[buffer(8)]]   // [B*H_q*S_q, D]
#
# Dispatch:  grid=(B*H_q*32, S_q, 1)  threadgroup=(32, 1, 1)
#
_FUSED_SDPA_SRC = r"""
    // 32 lanes per threadgroup; one threadgroup per (B*H_q, S_q) output cell
    uint q_head_idx = thread_position_in_grid.x / 32;
    uint q_pos      = thread_position_in_grid.y;
    uint lane       = thread_position_in_threadgroup.x;

    // Unpack shape pack
    uint H_q       = params[0];
    uint H_kv      = params[1];
    uint S_q       = params[2];
    uint S_kv      = params[3];
    uint D         = params[4];
    uint n_sub     = params[5];
    uint sub_dim   = params[6];
    uint n_sub_v   = params[7];
    uint sub_dim_v = params[8];
    uint flags     = params[9];

    bool causal       = (flags & 1u) != 0u;
    bool use_window   = (flags & 2u) != 0u;
    uint window_width = slide_arr[0];
    float scale       = scale_arr[0];

    if (q_pos >= S_q) { return; }

    uint batch  = q_head_idx / H_q;
    uint h_q    = q_head_idx % H_q;
    uint h_kv   = (h_q * H_kv) / H_q;        // GQA integer div

    uint q_base   = q_head_idx * S_q * D + q_pos * D;
    uint k_base_b = batch * H_kv * S_kv;     // K row stride
    uint out_base = q_head_idx * S_q * D + q_pos * D;

    constexpr uint kNCentroids = LUT_N_CENTROIDS;     // compile-time
    constexpr uint kMaxLut     = LUT_MAX_SIZE;        // n_sub * n_centroids
    constexpr uint kDimsPerLane = MAX_D / 32;         // output dims owned by each lane

    // LUT lives in threadgroup (shared across all lanes in the SIMD group).
    // t_out and tg_d_shared have been replaced by lane-local registers:
    //   my_out[kDimsPerLane]  — each lane owns D/32 output dimensions
    //   running_d             — denominator accumulated in registers
    threadgroup float lut[kMaxLut];

    // -----------------------------------------------------------------
    // Phase 0: fill the per-query LUT cooperatively.
    //   lut[sub * n_centroids + c] = q_sub_vec dot k_codebook_row
    //
    // Stripe (sub, centroid) pairs across 32 lanes — each lane computes
    // one dot product independently.  The pragma enables FMA contraction
    // on the inner dot loop; relaxed still honors INF/NaN unlike fast.
    // -----------------------------------------------------------------
    uint lut_total = n_sub * kNCentroids;
    for (uint idx = lane; idx < lut_total; idx += 32) {
        uint sub = idx / kNCentroids;
        uint c   = idx % kNCentroids;
        uint q_sub_off = q_base + sub * sub_dim;
        uint cb_off    = c * sub_dim;
        float dot = 0.0f;
        for (uint i = 0; i < sub_dim; ++i) {
            dot += q[q_sub_off + i] * k_codebook[cb_off + i];
        }
        lut[idx] = dot;
    }

    // -----------------------------------------------------------------
    // Phase 1: initialize lane-local running stats.
    //
    // my_out holds D/32 output floats owned by this lane.
    // running_m and running_d are pure register scalars — no threadgroup
    // writes needed.  The single barrier here lets all lanes finish writing
    // the LUT before any lane reads it in Phase 2.
    // -----------------------------------------------------------------
    float my_out[kDimsPerLane];
    for (uint k = 0; k < kDimsPerLane; ++k) {
        my_out[k] = 0.0f;
    }
    float running_m = -INFINITY;
    float running_d = 0.0f;

    threadgroup_barrier(mem_flags::mem_threadgroup);   // sole barrier: LUT ready

    // Convention: queries align to the tail of S_kv (standard decode pattern)
    uint q_abs = (S_kv - S_q) + q_pos;

    // -----------------------------------------------------------------
    // Phase 2: tiled online softmax + V accumulation — zero additional barriers
    // -----------------------------------------------------------------
    for (uint tile_start = 0; tile_start < S_kv; tile_start += 32) {
        uint k_pos = tile_start + lane;

        // Per-lane mask resolution
        float score = -INFINITY;
        bool valid = (k_pos < S_kv);
        if (valid && causal && k_pos > q_abs) valid = false;
        if (valid && use_window) {
            if (q_abs + 1u > window_width && k_pos + window_width < q_abs + 1u) {
                valid = false;
            }
        }
        if (valid) {
            uint k_row_idx = (k_base_b + h_kv * S_kv + k_pos) * n_sub;
            float s = 0.0f;
            for (uint sub = 0; sub < n_sub; ++sub) {
                uint c = k_indices[k_row_idx + sub];
                s += lut[sub * kNCentroids + c];
            }
            score = s * scale;
        }

        // SIMD-wide max — broadcasts result to all lanes, no barrier
        float tile_max = simd_max(score);
        if (!isfinite(tile_max)) { continue; }   // whole tile masked

        // Lane 0 computes the new max and rescale factor; simd_broadcast_first
        // propagates to all lanes without a threadgroup barrier.
        float m_old     = running_m;
        float m_new_l0  = max(m_old, tile_max);
        // metal::precise::exp guarantees exp(-inf)==0.0 regardless of math mode.
        float factor_l0 = isfinite(m_old) ? metal::precise::exp(m_old - m_new_l0) : 0.0f;
        float m_new  = simd_broadcast_first(m_new_l0);
        float factor = simd_broadcast_first(factor_l0);
        running_m = m_new;

        float w = metal::precise::exp(score - m_new);
        if (!valid) w = 0.0f;

        // Denominator: fully register-local, synced via simd_broadcast_first.
        // simd_sum broadcasts the tile sum to all lanes — no threadgroup write.
        float tile_w_sum = simd_sum(w);
        running_d = running_d * factor + simd_broadcast_first(tile_w_sum);

        // Rescale lane's owned output slice and accumulate V contribution.
        // Each lane owns output dimensions [lane*(D/32) .. (lane+1)*(D/32)-1].
        // No threadgroup array involved — pure register arithmetic.
        for (uint k = 0; k < kDimsPerLane; ++k) {
            my_out[k] *= factor;
        }

        // V accumulation: lane owns kDimsPerLane contiguous output dims.
        // Walk all 32 tile-mates via simd_shuffle to get their weights.
        for (uint k = 0; k < kDimsPerLane; ++k) {
            uint dim   = lane * kDimsPerLane + k;
            uint sub_v = dim / sub_dim_v;
            uint comp  = dim % sub_dim_v;
            float acc = 0.0f;
            for (uint l = 0; l < 32; ++l) {
                uint k_l = tile_start + l;
                if (k_l >= S_kv) break;
                float w_l = simd_shuffle(w, l);
                if (w_l == 0.0f) continue;
                uint v_row_idx = (k_base_b + h_kv * S_kv + k_l) * n_sub_v;
                uint v_c = v_indices[v_row_idx + sub_v];
                acc += w_l * v_codebook[v_c * sub_dim_v + comp];
            }
            my_out[k] += acc;
        }
        // No threadgroup barrier — all output state is lane-local.
    }

    // -----------------------------------------------------------------
    // Phase 3: normalize and write each lane's owned dims directly to device.
    // running_d is identical in all lanes (kept in sync via simd_broadcast_first).
    // -----------------------------------------------------------------
    float inv_d = 1.0f / max(running_d, 1e-20f);
    for (uint k = 0; k < kDimsPerLane; ++k) {
        uint dim = lane * kDimsPerLane + k;
        out[out_base + dim] = my_out[k] * inv_d;
    }
"""


# ---------------------------------------------------------------------------
# Compile cache — one kernel per (n_centroids, n_sub, D) tuple
# ---------------------------------------------------------------------------
_kernel_cache: dict = {}

# Public caps; raise these only after benchmarking threadgroup memory budget.
MAX_N_CENTROIDS = 256
MAX_N_SUB = 16
MAX_HEAD_DIM = 256


def supports_shape(n_centroids: int, n_sub: int, head_dim: int) -> bool:
    """Quick check for whether a configuration fits the kernel's caps."""
    return (
        1 <= n_centroids <= MAX_N_CENTROIDS
        and 1 <= n_sub <= MAX_N_SUB
        and 1 <= head_dim <= MAX_HEAD_DIM
    )


def _get_kernel(n_centroids: int, n_sub: int, D: int):
    if n_centroids > MAX_N_CENTROIDS:
        raise ValueError(
            f"Fused SDPA kernel: n_centroids must be <= {MAX_N_CENTROIDS}, got {n_centroids}."
        )
    if n_sub > MAX_N_SUB:
        raise ValueError(f"Fused SDPA kernel: n_sub must be <= {MAX_N_SUB}, got {n_sub}.")
    if D > MAX_HEAD_DIM:
        raise ValueError(f"Fused SDPA kernel: head_dim must be <= {MAX_HEAD_DIM}, got {D}.")
    if D % 32 != 0:
        raise ValueError(
            f"Fused SDPA kernel: head_dim must be a multiple of 32 "
            f"(lane-owned output layout), got D={D}."
        )
    key = (n_centroids, n_sub, D)
    if key not in _kernel_cache:
        src = (
            _FUSED_SDPA_SRC.replace("LUT_N_CENTROIDS", str(n_centroids))
            .replace("LUT_MAX_SIZE", str(n_sub * n_centroids))
            .replace("MAX_D", str(D))
        )
        # #pragma METAL fp must appear at file scope (not inside a compound
        # statement).  MLX injects `header` before the kernel body, so this
        # is the correct place.  'relaxed' mode honors INF/NaN unlike 'fast'
        # and enables FMA contraction across statements for the LUT dot loop.
        header = "#pragma METAL fp math_mode(relaxed)\n"
        _kernel_cache[key] = mx.fast.metal_kernel(
            name=f"vecinfer_fused_sdpa_c{n_centroids}_s{n_sub}_d{D}",
            input_names=[
                "q",
                "k_indices",
                "k_codebook",
                "v_indices",
                "v_codebook",
                "params",
                "scale_arr",
                "slide_arr",
            ],
            output_names=["out"],
            header=header,
            source=src,
            ensure_row_contiguous=True,
        )
    return _kernel_cache[key]


# ===========================================================================
# Public API
# ===========================================================================
def metal_fused_sdpa(
    q_tilde: mx.array,  # [B, H_q, S_q, D]   fp32 — already transformed
    k_indices: mx.array,  # [B, H_kv, S_kv, n_sub]
    k_codebook: mx.array,  # [n_centroids, sub_dim]
    v_indices: mx.array,  # [B, H_kv, S_kv, n_sub_v]
    v_codebook: mx.array,  # [n_centroids_v, sub_dim_v]
    scale: float,
    *,
    causal: bool = True,
    sliding_window: int = 0,
    out_dtype: Optional[mx.Dtype] = None,
) -> mx.array:
    """Compute fused SDPA from VecInfer compressed K/V indices.

    The reference math is the same as :func:`reference_sdpa` in the
    proof script::

        out = softmax((q_tilde @ K_tilde.T) * scale) @ V_hat

    where ``K_tilde`` is the smooth+Hadamard-transformed key tensor.
    By contract ``q_tilde @ K_tilde.T == q @ K_hat.T`` (VecInfer Eq. 7),
    so the result is mathematically identical to running standard SDPA
    on the dequantized fp16 K_hat — but we never have to materialize it.

    Args:
        q_tilde: ``[B, H_q, S_q, D]`` queries already passed through
            :func:`apply_dual_transform_queries`.  Cast to fp32 internally.
        k_indices: ``[B, H_kv, S_kv, n_sub]`` int / uint codebook indices
            for keys (in transformed space).
        k_codebook: ``[n_centroids, sub_dim]`` centroid table.
        v_indices: ``[B, H_kv, S_kv, n_sub_v]`` value indices.
        v_codebook: ``[n_centroids_v, sub_dim_v]`` value centroid table.
        scale: Attention scale (usually ``1 / sqrt(head_dim)``).
        causal: Apply causal mask (queries align to tail of S_kv).
        sliding_window: If > 0, only attend to the last ``sliding_window``
            keys before each query position.
        out_dtype: Output dtype.  Defaults to ``q_tilde.dtype``; cast on
            return for fp16/fp32 callers.

    Returns:
        ``[B, H_q, S_q, D]`` attention output.

    Raises:
        ValueError: If ``n_centroids``, ``n_sub`` or ``D`` exceed the
            kernel's compile-time caps (see module docstring).
    """
    B, H_q, S_q, D = q_tilde.shape
    _, H_kv, S_kv, n_sub = k_indices.shape
    n_centroids, sub_dim = k_codebook.shape
    _, _, _, n_sub_v = v_indices.shape
    n_centroids_v, sub_dim_v = v_codebook.shape

    if D != n_sub * sub_dim:
        raise ValueError(f"fused_sdpa: D={D} must equal n_sub*sub_dim={n_sub * sub_dim}.")
    if D != n_sub_v * sub_dim_v:
        raise ValueError(f"fused_sdpa: D={D} must equal n_sub_v*sub_dim_v={n_sub_v * sub_dim_v}.")
    if n_centroids != n_centroids_v:
        raise ValueError(
            "fused_sdpa: key and value codebooks must currently have the same "
            f"n_centroids (got {n_centroids} vs {n_centroids_v})."
        )
    if H_q % H_kv != 0:
        raise ValueError(f"fused_sdpa: H_q={H_q} must be a multiple of H_kv={H_kv}.")

    in_dtype = q_tilde.dtype
    if out_dtype is None:
        out_dtype = in_dtype

    q_flat = q_tilde.reshape(B * H_q * S_q, D).astype(mx.float32)
    k_idx_flat = k_indices.reshape(B * H_kv * S_kv, n_sub).astype(mx.uint32)
    v_idx_flat = v_indices.reshape(B * H_kv * S_kv, n_sub_v).astype(mx.uint32)
    k_cb = k_codebook.astype(mx.float32)
    v_cb = v_codebook.astype(mx.float32)

    flags = 0
    if causal:
        flags |= 1
    if sliding_window and sliding_window > 0:
        flags |= 2

    params = mx.array(
        [H_q, H_kv, S_q, S_kv, D, n_sub, sub_dim, n_sub_v, sub_dim_v, flags],
        dtype=mx.uint32,
    )
    scale_arr = mx.array([float(scale)], dtype=mx.float32)
    slide_arr = mx.array([int(sliding_window or 0)], dtype=mx.uint32)

    kernel = _get_kernel(n_centroids, n_sub, D)

    outputs = kernel(
        inputs=[q_flat, k_idx_flat, k_cb, v_idx_flat, v_cb, params, scale_arr, slide_arr],
        output_shapes=[(B * H_q * S_q, D)],
        output_dtypes=[mx.float32],
        grid=(B * H_q * 32, S_q, 1),
        threadgroup=(32, 1, 1),
    )
    out = outputs[0].reshape(B, H_q, S_q, D)
    if out_dtype != mx.float32:
        out = out.astype(out_dtype)
    return out


# ===========================================================================
# mlx_lm dispatcher patch
# ===========================================================================
#
# mlx_lm.models.base.scaled_dot_product_attention is the single SDPA entry
# point every model architecture calls.  It already dispatches on
# hasattr(cache, "bits") for the quantized-cache path; we extend the same
# dispatch to honor hasattr(cache, "fused_sdpa").
#
# The patch is idempotent and reversible (call unpatch_mlx_lm to restore).

_original_sdpa = None
_patched: bool = False


def patch_mlx_lm_for_fused_sdpa() -> None:
    """Monkey-patch ``mlx_lm.models.base.scaled_dot_product_attention`` so
    that any cache exposing a ``fused_sdpa(q, scale, *, causal, sliding_window)``
    method receives the attention call directly — bypassing the standard
    materialize-then-attend path.

    Safe to call multiple times.  Call :func:`unpatch_mlx_lm` to restore.
    """
    global _original_sdpa, _patched
    if _patched:
        return

    import mlx_lm.models.base as _base

    _original_sdpa = _base.scaled_dot_product_attention

    def _patched_sdpa(queries, keys, values, cache, scale, mask, sinks=None):
        # NOTE: as of 0.6.0 the dispatcher is a no-op in the live
        # generation loop because VecInferKVCache.update_and_fetch still
        # returns the standard fp16 K_hat/V_hat tensors, which mlx_lm's
        # default SDPA handles efficiently.  Profiling on Llama-3.1-8B
        # showed that the fused kernel cannot beat MLX SDPA on an already-
        # materialized K_hat tensor because the per-step dequant cost is
        # amortized to zero by mlx_lm's persistent cache buffer.
        #
        # cache.fused_sdpa(q) remains available for callers who want it
        # explicitly (e.g. memory-bound configurations that skip the K_hat
        # buffer entirely).  This dispatcher would route to it if mlx_lm
        # ever stops returning a usable fp16 tensor from update_and_fetch.
        return _original_sdpa(
            queries, keys, values, cache=cache, scale=scale, mask=mask, sinks=sinks
        )

    _base.scaled_dot_product_attention = _patched_sdpa
    _patched = True


def unpatch_mlx_lm() -> None:
    """Restore the original ``mlx_lm.models.base.scaled_dot_product_attention``."""
    global _original_sdpa, _patched
    if not _patched:
        return
    import mlx_lm.models.base as _base

    _base.scaled_dot_product_attention = _original_sdpa
    _patched = False


def is_patched() -> bool:
    """True if :func:`patch_mlx_lm_for_fused_sdpa` is currently active."""
    return _patched


__all__ = [
    "metal_fused_sdpa",
    "supports_shape",
    "MAX_N_CENTROIDS",
    "MAX_N_SUB",
    "MAX_HEAD_DIM",
    "patch_mlx_lm_for_fused_sdpa",
    "unpatch_mlx_lm",
    "is_patched",
]
